### ISSUE TITLE
[Bug]: Error loading spatial structure on model with IfcAlignment

### ISSUE THREAD

**Issue by MichalNekvasil** [ThatOpen/engine_web-ifc#776]
### What happened?

Hello, I try to get spatial structure from model (viewer.IFC.getSpatialStructure(modelID, true)), but it crashes on line with IfcAlignment. 
![image](https://github.com/ThatOpen/engine_web-ifc/assets/16255036/776722a7-c700-4eb3-861c-c761ef8a062b)

I will attach the model too. There is no problem opening it in BIMVision for example ...
[model_001.zip](https://github.com/ThatOpen/engine_web-ifc/files/15009486/model_001.zip)

Thank you for your help

Have a nice day
Michal Nekvasil

### Version

0.0.5

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
web-ifc-api.js:72377 Uncaught (in promise) TypeError: FromRawLineData[this.modelSchemaList[modelID]][rawLineData.type] is not a function
    at IfcAPI2.GetLine (web-ifc-api.js:72377:1)
    at WebIfcPropertyManager.getItemProperties (WebIfcPropertyManager.ts:8:31)
    at WebIfcPropertyManager.getChildren (BasePropertyManager.ts:34:47)
    at async WebIfcPropertyManager.getSpatialNode (BasePropertyManager.ts:21:9)
    at async WebIfcPropertyManager.getChildren (BasePropertyManager.ts:37:13)
    at async WebIfcPropertyManager.getSpatialNode (BasePropertyManager.ts:21:9)
    at async WebIfcPropertyManager.getSpatialStructure (WebIfcPropertyManager.ts:20:9)
    at async PropertyManager.getSpatialStructure (PropertyManager.ts:70:16)
    at async getTreeData (TreeViewModelStructure.tsx:324:31)
```

**Comment by MichalNekvasil** [comment]
Is there any progress?

**Comment by beachtom** [comment]
Sorry no solution as of yet.

**Comment by beachtom** [comment]
Just fixed it!
